//
// Created by ftfunjth on 2020/3/14.
//

#ifndef FTPSERVER_FTPOPERATOR_H
#define FTPSERVER_FTPOPERATOR_H

#include "FTPSession.h"
#define FTP_OPERATOR_DECLARE(command)                                 \
    extern void command(FTPSession *session, ACE_SOCK_Stream &socket, \
                        std::string &suffix)

FTP_OPERATOR_DECLARE(AUTH);
FTP_OPERATOR_DECLARE(LIST);
FTP_OPERATOR_DECLARE(USER);
FTP_OPERATOR_DECLARE(PASV);
FTP_OPERATOR_DECLARE(PORT);
FTP_OPERATOR_DECLARE(SIZE);
FTP_OPERATOR_DECLARE(PASS);
FTP_OPERATOR_DECLARE(PWD);
FTP_OPERATOR_DECLARE(TYPE);
FTP_OPERATOR_DECLARE(CWD);
FTP_OPERATOR_DECLARE(RETR);
FTP_OPERATOR_DECLARE(STOR);
FTP_OPERATOR_DECLARE(MKD);
FTP_OPERATOR_DECLARE(SYST);
FTP_OPERATOR_DECLARE(FEAT);
FTP_OPERATOR_DECLARE(MDTM);
FTP_OPERATOR_DECLARE(OPTS);
FTP_OPERATOR_DECLARE(MLSD);
FTP_OPERATOR_DECLARE(MLST);
FTP_OPERATOR_DECLARE(DELE);
FTP_OPERATOR_DECLARE(QUIT);
FTP_OPERATOR_DECLARE(RNFR);
FTP_OPERATOR_DECLARE(RNTO);
FTP_OPERATOR_DECLARE(SITE);
FTP_OPERATOR_DECLARE(NOOP);
FTP_OPERATOR_DECLARE(MODE);
FTP_OPERATOR_DECLARE(EPSV);
FTP_OPERATOR_DECLARE(RMD);
#endif  // FTPSERVER_FTPOPERATOR_H
